### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by DanielVandH** [JuliaGeometry/AdaptivePredicates.jl#11]
Just tracking what I need to do still...

- [ ] Translate all the remaining arithmetic functions 
- [ ] Translate `orient2dfast`, `orient2dexact`, `orient2dslow`, `orient2d` (partially done by vchuravy already)
- [ ] Translate `orient3dfast`, `orient3dexact`, `orient3dslow`, `orient3d`
- [ ] Translate `incirclefast`, `incircleexact`, `incircleslow`, `incircle`
- [ ] Translate `inspherefast`, `insphereexact`, `insphereslow`, `insphere`
- [ ] Add variants of `orient2d` that continue adapting up some precision (like 1/2% as suggested in Shewchuk's paper I think) for the purpose of computing the area of a triangle. I think there's also a trick mentioned about computing intersections somewhere..
- [ ] Add support for both `Float64` and `Float32`. `Float32` means I can let DelaunayTriangulation.jl work with `Float32` too.
- [ ] Document all the functions and the use of the package. 
- [ ] Test all the functions and also make better use of Supposition.jl.
- [ ] Register

Hopefully everything can get working so I can actually test it all in a proper environment (i.e. just putting it directly into DelaunayTriangulation.jl and seeing what happens).
